apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-runner
  namespace: wikistream
rules:
  # Flink создает/читает pods, services, configmaps, events
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - configmaps
      - events
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # ВАЖНО: deployments/replicasets в группе apps (у тебя сейчас именно это падает)
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["get", "list", "watch"]

  # Иногда Flink трогает endpoint’ы (зависит от версии/режима)
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]