apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: wiki-processing-secrets
  namespace: {{ .Release.Namespace }}
spec:
  serviceAccountName: {{ .Values.serviceAccount.name }}
  secretProviderClassName: wiki-processing-sm
  secretObject:
    type: Opaque
    data:
      - sourcePath: "GCS_BUCKET"
        targetKey: "GCS_BUCKET"
      - sourcePath: "KAFKA_BOOTSTRAP_SERVERS"
        targetKey: "KAFKA_BOOTSTRAP_SERVERS"
      - sourcePath: "KAFKA_SASL_USERNAME_PROCESSING"
        targetKey: "KAFKA_SASL_USERNAME_PROCESSING"