{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wiki-processing.serviceAccountName" . }}
  labels:
{{ include "wiki-processing.labels" . | indent 4 }}
  annotations:
    {{- if .Values.serviceAccount.gsaEmail }}
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gsaEmail | quote }}
    {{- end }}
{{- end }}