image:
  repository: europe-west3-docker.pkg.dev/PROJECT_ID/wiki-stream-analytics/wiki-producer
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

serviceAccount:
  create: true
  name: producer-sa
  annotations: {}

env:
  # App config
  WIKI_SSE_URL: "https://stream.wikimedia.org/v2/stream/recentchange"
  KAFKA_TOPIC: "recentchange_raw"
  WIKI_USER_AGENT: "wiki-stream-analytics/0.1 (contact: you@example.com)"
  WIKI_DEFAULT_TIMEOUT: "30"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}