apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wiki-producer.fullname" . }}-env
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}