name: CI

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint (mypy/black/ruff)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --group producer --group dev --frozen

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: ty
        run: make ty

      - name: black (check)
        run: make black

      - name: ruff
        run: make ruff

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      fail-fast: false
      matrix:
        marker: [unit, integration]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --group producer --group dev --frozen

      - name: Run pytest (-m ${{ matrix.marker }})
        run: uv run pytest ./producer/tests/ -m ${{ matrix.marker }} -q

  build:
    name: Build image
    environment: prod
    needs: [lint, tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.CI_SA_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2

      # Configure Docker auth for Artifact Registry
      - name: Configure docker auth
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

      - name: Debug
        env:
          REGION: europe-west3
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REPO: ${{ secrets.AR_REPO }}          # e.g. "containers"
          IMAGE: wiki-producer
          TAG: ${{ github.sha }}
          STAGING_BUCKET: ${{ secrets.STAGING_BUCKET }}
        run: |
          set -eux

          echo "== gcloud identity =="
          gcloud auth list
          echo "active account: $(gcloud config get-value account)"
          echo "project: $(gcloud config get-value project)"

          echo "== buckets in project =="
          gcloud storage buckets list || true

          echo "== try access default cloudbuild bucket =="
          gcloud storage ls "gs://${STAGING_BUCKET}" || true

          gcloud storage buckets describe "gs://${STAGING_BUCKET}"

      - name: Build & Push
        env:
          REGION: europe-west3
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REPO: ${{ secrets.AR_REPO }}          # e.g. "containers"
          IMAGE: wiki-producer
          TAG: ${{ github.sha }}
          STAGING_BUCKET: ${{ secrets.STAGING_BUCKET }}

        run: |
          gcloud builds submit \
          --config producer/cloudbuild.yaml \
          --gcs-source-staging-dir "gs://${STAGING_BUCKET}/source" \
          --substitutions=_TAG=$GITHUB_SHA \
          .